# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20171204_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe_Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('id_ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Ingredient')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='id_equipment',
        ),
        migrations.AddField(
            model_name='recipe_ingredient',
            name='quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe_equipment',
            name='id_recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
    ]
