# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20171205_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='recipe_ingredient',
            name='id_type_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Type_Ingredient'),
        ),
    ]
