# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20171205_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unity',
            field=models.CharField(choices=[('GR', 'Gr'), ('KG', 'Kg')], default='GR', max_length=2),
        ),
    ]
