# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20171206_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='type_ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Type_Ingredient'),
        ),
    ]
