# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-09 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20171206_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.RenameField(
            model_name='recipe_ingredient',
            old_name='id_recipe',
            new_name='recipe',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='unit_dimension',
        ),
        migrations.RemoveField(
            model_name='recipe_ingredient',
            name='id_ingredient',
        ),
        migrations.RemoveField(
            model_name='recipe_ingredient',
            name='id_type_ingredient',
        ),
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='medida',
            field=models.CharField(choices=[('L', 'Litre'), ('M3', 'Cubic Metric'), ('GAL', 'Gallon')], default='L', max_length=3),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.Recipe_Ingredient', to='recipes.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipe_ingredient',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Ingredient'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='type_equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Type_Equipment'),
        ),
    ]
