# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20180129_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
